name: check
on: 
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18, 20]
        # os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # registry-url: 'https://registry.npmjs.org'
        cache: 'yarn'
    - run: yarn install
    - run: yarn audit
    - run: yarn lint
